version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/docker/volumes/pgdata/_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=django
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
